[build]
builder = "NIXPACKS"
buildCommand = "python -m ensurepip --upgrade && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
